### ISSUE TITLE
Add possibility to specifiy folder to publish

### ISSUE THREAD

**Issue by alxgrk** [debashish2014/local-package-publisher#1]
Hey,

this is a really useful library, thanks for sharing it!

However, for my current problem I'm trying to locally publish an Angular library, so the contents to be published lie under `dist/`. I think the easiest would be, to have another CLI option to specify the path to be published. Do you think this is possible to be added?

Thanks in advance
Alex

**Comment by debashish2014** [comment]
Hi @alxgrk, thank you for your kind words of appreciation.

Probably, you are missing the "files" property in package.json. It takes an array. Whichever files you want to be part of the package, please add it this files array:

Ex. package.json
If we want index.js and package.json to be part of the contents of the package you want to publish, the files array would look like this.

`
{

       "files": [
            "index.js",
            "package.json"
        ],

 }
`

In your case, it will look as below:

`
{

       "files": [
            "dist",
            "package.json"
        ],

 }
`

Please check https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files for further details.

Just wanted to inform you that I am closing this issue.
