### ISSUE TITLE
Breaks with `npx`

### ISSUE THREAD

**Issue by ProLoser** [debashish2014/local-package-publisher#7]
I tried publishing 2 packages with `npx local-package-publisher -p` and the second time there was problem accessing the cache.

I then tried to install the package globally but the cache is still broken and now I don't know how to fix it.

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/67395/219176898-5cb53db7-aeaf-401b-b1f3-294fa1afd53e.png">

**Comment by codepearlex** [comment]
I tried to install the package globally, but I'm facing the same issue shown in your screenshot  using npm `6.14.15` and node `14.18.1`.

**Comment by ProLoser** [comment]
I gave up on this tool. Instead I'm using the "resolutions" field in the root of my yarn monorepo and pointing to local file directories using "file:../other-project/packages/unpublished-package" which automatically copies the files (you can delete and recopy with "yarn install --check-files") without trying to locate the package on the registry first. Also allows you to keep your code and dependencies setup in their production configurations for better consistency

**Comment by debashish2014** [comment]
I'm sorry for the delay in fixing the issue. I was not getting time to maintain this project because of other projects' workloads. 

Please install version 1.0.5 of the tool globally using the npm command instead and give it a try.

I just wanted to let you know that I'm closing the issue for now.
